# Application Name
spring.application.name=personal-finance-manager

# H2 Configuration (Used for REST tests)
spring.datasource.url=jdbc:h2:mem:pfm_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Flyway
spring.flyway.enabled=true

# JPA Configuration
# Setting to 'update' for now to allow H2 tests to run without Flyway complexity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable security for initial bootstrapping
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
